source "https://rubygems.org"

gemspec

# Exclude development-only gems from dependabot.
unless ENV["DEPENDABOT"]
  gem "aws-sigv4"
  gem "webmock", "~> 3.0"
  gem "irb"

  gem "rake"
  gem "rspec", "~> 3.11"

  # Exclude development-only gems from the gemfiles generated by appraisal.
  unless defined?(::Appraisal::Gemfile) && is_a?(::Appraisal::Gemfile)
    gem "appraisal", require: false
    gem "standard", require: false
    gem "simplecov", require: false
    gem "yard", require: false
  end
end

gem "prompt_builder", path: "../prompt_builder" # local development path
