#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "irb"

require_relative "initialize"

puts "=" * 80
puts "PatientHttp Interactive Console"
puts "=" * 80
puts ""

IRB.start
