source "https://rubygems.org"

gem "patient_http", path: "../../patient_http"
gem "patient_http-sidekiq", path: "../../patient_http-sidekiq"
gem "prompt_builder", path: "../../prompt_builder"
gem "patient_llm", path: ".."

gem "dotenv"
gem "protocol-rack"
gem "rack-session"
gem "json"
gem "irb"
gem "activesupport"
